# Generated by Django 2.1 on 2018-09-26 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fechaInicio',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='hora_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
