# Generated by Django 2.1 on 2018-10-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_auto_20180926_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='idm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
