# Generated by Django 2.1 on 2018-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('domicilio', models.CharField(max_length=200)),
                ('nro_contrato', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=200)),
            ],
        ),
    ]
