# Generated by Django 2.1 on 2018-09-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20180924_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Zona'),
        ),
    ]
