# Generated by Django 2.1 on 2018-09-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20180926_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Zona'),
        ),
    ]
