# Generated by Django 2.1 on 2018-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='coordenada',
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_identificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(default='c/ sakjdla', max_length=300),
            preserve_default=False,
        ),
    ]
