# Generated by Django 2.1 on 2018-09-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_auto_20180920_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='coordenada',
        ),
        migrations.AlterField(
            model_name='area',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Punto'),
        ),
    ]
