# Generated by Django 2.1 on 2018-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20180921_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='punto',
        ),
        migrations.AddField(
            model_name='area',
            name='punto',
            field=models.ManyToManyField(to='empleado.Punto'),
        ),
    ]
