# Generated by Django 2.1 on 2018-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_remove_estadoempleado_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='costo',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
